title: Chirag Gupta
position: Ph.D. Student
affiliation: Carnegie Mellon University
email: cgupta61@bloomberg.net
keywords: machine learning, statistics, uncertainty, optimization
google_scholar: https://scholar.google.com/citations?user=2ALBM1sAAAAJ&hl=en
github_link: https://github.com/AIgen/
avatar: ./assets/img/profile.jpg
google_analytics: UA-111818401-1
favicon: ./assets/img/faviconCMU.png
favicon_dark: ./assets/img/faviconCMU.png
description: This is a simple personal homepage based on the Minimal Light theme. 
canonical: https://AIgen.github.io/
remote_theme: yaoyao-liu/minimal-light
